const signals = (await Deno.readTextFile("../_input/13.txt"))
  .split("\n\n")
  .map((line) => line.split("\n").map(eval))

const sum = signals.map(([left, right], index) => {
  return comparePacketData(left, right) ? index + 1 : 0
}).reduce((a, b) => a + b)

console.log("Part 1:", sum)

// generated by ChatGPT
function comparePacketData(left, right) {
  // Convert integers to single-element lists
  if (typeof left === 'number') left = [left];
  if (typeof right === 'number') right = [right];

  // Compare lists by their elements
  for (let i = 0; i < left.length && i < right.length; i++) {
    // If both elements are integers, compare them by their numerical values
    if (typeof left[i] === 'number' && typeof right[i] === 'number') {
      if (left[i] < right[i]) return true;  // Left is smaller
      if (left[i] > right[i]) return false; // Left is larger
    }
    // Otherwise, recursively compare the elements
    else {
      if (comparePacketData(left[i], right[i])) return true;  // Left is smaller
      if (comparePacketData(right[i], left[i])) return false; // Left is larger
    }
  }

  // If we haven't returned yet, the lists are the same up to the length of the shorter list
  // If the left list is shorter, it is considered smaller
  return left.length < right.length;
}
